### ISSUE TITLE
The transform BigQueryIO.Read is currently not supported.

### ISSUE THREAD

**Issue by ravwojdyla** [dataArtisans/flink-dataflow#20]
```
[main] INFO com.dataartisans.flink.dataflow.FlinkPipelineRunner - Executing pipeline using FlinkPipelineRunner.
[main] INFO com.dataartisans.flink.dataflow.FlinkPipelineRunner - Translating pipeline to Flink program.
enterCompositeTransform- a5f5b96null
|   visitTransform- 40ab1491BigQueryIO.Read
class com.google.cloud.dataflow.sdk.io.BigQueryIO$Read$Bound
java.lang.UnsupportedOperationException: The transform BigQueryIO.Read is currently not supported.
  at com.dataartisans.flink.dataflow.translation.FlinkBatchPipelineTranslator.visitTransform(FlinkBatchPipelineTranslator.java:107)
  at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:219)
  at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
  at com.google.cloud.dataflow.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:102)
  at com.google.cloud.dataflow.sdk.Pipeline.traverseTopologically(Pipeline.java:259)
  at com.dataartisans.flink.dataflow.translation.FlinkPipelineTranslator.translate(FlinkPipelineTranslator.java:32)
  at com.dataartisans.flink.dataflow.FlinkPipelineExecutionEnvironment.translate(FlinkPipelineExecutionEnvironment.java:128)
  at com.dataartisans.flink.dataflow.FlinkPipelineRunner.run(FlinkPipelineRunner.java:115)
  at com.dataartisans.flink.dataflow.FlinkPipelineRunner.run(FlinkPipelineRunner.java:48)
```

Would be nice to support BQ IO

**Comment by mxm** [comment]
+1 Would be nice. It'll come with the Beam integration process!
