### ISSUE TITLE
Unable to serialize exception running KafkaWindowedWordCountExample

### ISSUE THREAD

**Issue by ecesena** [dataArtisans/flink-dataflow#8]
I'm trying to run `KafkaWindowedWordCountExample`, but I get an "unable to serialize" exception.
I tried both with Flink 0.10.2 and 0.10.1.

Basically what I did was to create a fat jar including all deps, then run flink:
```
$ flink run -C file:///path/to/fat.jar -c com.dataartisans.flink.dataflow.examples.streaming.KafkaWindowedWordCountExample /path/to/flink-dataflow-0.2.jar

...

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:512)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:395)
	at org.apache.flink.client.program.Client.runBlocking(Client.java:252)
	at org.apache.flink.client.CliFrontend.executeProgramBlocking(CliFrontend.java:676)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:326)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:978)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1028)
Caused by: java.lang.IllegalArgumentException: unable to serialize com.dataartisans.flink.dataflow.translation.wrappers.streaming.io.UnboundedFlinkSource@6e5479cb
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:51)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:81)
	at com.google.cloud.dataflow.sdk.io.Read$Unbounded.<init>(Read.java:169)
	at com.google.cloud.dataflow.sdk.io.Read$Unbounded.<init>(Read.java:164)
	at com.google.cloud.dataflow.sdk.io.Read.from(Read.java:66)
	at com.dataartisans.flink.dataflow.examples.streaming.KafkaWindowedWordCountExample.main(KafkaWindowedWordCountExample.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:497)
	... 6 more
Caused by: java.io.NotSerializableException: com.google.cloud.dataflow.sdk.options.ProxyInvocationHandler
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1180)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1528)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1493)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1528)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1493)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:47)
	... 16 more
```

Any idea? Thanks, E.

**Comment by ecesena** [comment]
Solved - I was using Dataflow 1.4.0, while flink-dataflow seems to support 1.0.0.

**Comment by mxm** [comment]
Thanks for letting us know @ecesena! We will soon update to the latest Dataflow version.

**Comment by ecesena** [comment]
Thank would be great!
